#!/bin/sh

echo "Be sure to run this script as root."
if [ $# -eq "0" ]; then
   echo "Removing old index."
   rm -rf /Users/ella01/Desktop/webdsl_todolist/ToDoListApp/searchindex/ToDoListApp
fi
echo "Creating new index, this may take a while."
ant reindex -Dentities="$*"
chmod -R 777 /Users/ella01/Desktop/webdsl_todolist/ToDoListApp/searchindex/ToDoListApp
echo "Done."